# Generated by Django 4.2 on 2023-04-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commnet',
            new_name='comment',
        ),
    ]
