# Generated by Django 4.2 on 2023-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_commnet_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
